import os
import json
import threading
import subprocess
import sys
import multiprocessing
import customtkinter as ctk
from tkinter import messagebox

from pc_detection import get_pc_specs
from ui_widgets import ToolTip
from settings_dialog import SettingsDialog
from tab_search import SearchOptimizeTab
from tab_local import LocalGamesTab
from tab_network import NetworkSpeedTab

CACHE_FILE = "benchmark_cache.json"

ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")

class HardwareOptimizerApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title("Game Optimizer")
        self.geometry("1020x780")
        self.minsize(920, 700)

        self.cpu_score = 0
        self.ram_score = 0
        self.gpu_score = 0
        self.disk_score = 0
        self.benchmark_process = None
        self.actual_specs = get_pc_specs()
        
        self.setting_enable_fg = ctk.BooleanVar(value=True)
        self.setting_enable_rt = ctk.BooleanVar(value=True)
        self.setting_fps_format = ctk.StringVar(value="Show Range (Min - Max)")
        
        self.settings_window = None

        self.load_cached_data()
        self.create_widgets()
        self.update_score_displays()

    def load_cached_data(self):
        if os.path.exists(CACHE_FILE):
            try:
                with open(CACHE_FILE, "r") as file:
                    data = json.load(file)
                    self.cpu_score = data.get("cpu_score", 0)
                    self.ram_score = data.get("ram_score", 0)
                    self.gpu_score = data.get("gpu_score", 0)
                    self.disk_score = data.get("disk_score", 0)
            except Exception:
                pass

    def save_cached_data(self):
        data = {
            "cpu_score": self.cpu_score,
            "ram_score": self.ram_score,
            "gpu_score": self.gpu_score,
            "disk_score": self.disk_score
        }
        with open(CACHE_FILE, "w") as file:
            json.dump(data, file)
            
    def get_tier_info(self, score, component):
        if score == 0:
            return "Not Tested", "gray"
        if component == "CPU":
            if score < 10000: return "Entry Level", "#e74c3c"
            if score < 20000: return "Mid-Range", "#f39c12"
            if score < 35000: return "High-End", "#2ecc71"
            return "Enthusiast", "#9b59b6"
        elif component == "RAM":
            if score < 2000: return "Entry Level", "#e74c3c"
            if score < 3500: return "Mid-Range", "#f39c12"
            if score < 6000: return "High-End", "#2ecc71"
            return "Enthusiast", "#9b59b6"
        elif component == "GPU":
            if score < 5000: return "Entry Level", "#e74c3c"
            if score < 10000: return "Mid-Range", "#f39c12"
            if score < 18000: return "High-End", "#2ecc71"
            return "Enthusiast", "#9b59b6"
        elif component == "DISK":
            if score < 2000: return "Entry Level", "#e74c3c"
            if score < 5000: return "Mid-Range", "#f39c12"
            if score < 10000: return "High-End", "#2ecc71"
            return "Enthusiast", "#9b59b6"

    def create_widgets(self):
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=1)

        # ---------------- SIDEBAR ----------------
        self.sidebar_frame = ctk.CTkFrame(self, width=290, corner_radius=0, fg_color=("gray90", "gray17"))
        self.sidebar_frame.grid(row=0, column=0, sticky="nsew")
        self.sidebar_frame.grid_rowconfigure(8, weight=1)

        self.logo_label = ctk.CTkLabel(self.sidebar_frame, text="Game Optimizer", font=ctk.CTkFont(family="Segoe UI", size=24, weight="bold"))
        self.logo_label.grid(row=0, column=0, padx=20, pady=(20, 10))
        ToolTip(self.logo_label, "Game Optimizer - Hardware Performance & FPS Suite (Beta 1.0)")

        self.scores_frame = ctk.CTkFrame(self.sidebar_frame, fg_color="transparent")
        self.scores_frame.grid(row=1, column=0, padx=20, pady=5, sticky="ew")

        self.score_title_frame = ctk.CTkFrame(self.scores_frame, fg_color="transparent")
        self.score_title_frame.pack(fill="x", pady=(0, 10))
        self.score_title = ctk.CTkLabel(self.score_title_frame, text="System Scores:", font=ctk.CTkFont(size=14, weight="bold"))
        self.score_title.pack(side="left")
        ToolTip(self.score_title, "These are the scores generated by the built-in benchmark.")
        
        self.edit_btn = ctk.CTkButton(self.score_title_frame, text="✏️ Edit", width=50, height=20, font=ctk.CTkFont(size=11), command=self.open_edit_dialog)
        self.edit_btn.pack(side="right")
        ToolTip(self.edit_btn, "Manually edit your hardware scores.\nGreat for simulating hardware upgrades.")

        self.cpu_frame = ctk.CTkFrame(self.scores_frame, fg_color="transparent")
        self.cpu_frame.pack(fill="x", pady=5)
        self.cpu_label = ctk.CTkLabel(self.cpu_frame, text="CPU: 0 pts", justify="left")
        self.cpu_label.pack(side="left")
        self.cpu_tier = ctk.CTkLabel(self.cpu_frame, text="", font=ctk.CTkFont(weight="bold"))
        self.cpu_tier.pack(side="right")
        
        self.ram_frame = ctk.CTkFrame(self.scores_frame, fg_color="transparent")
        self.ram_frame.pack(fill="x", pady=5)
        self.ram_label = ctk.CTkLabel(self.ram_frame, text="RAM: 0 pts", justify="left")
        self.ram_label.pack(side="left")
        self.ram_tier = ctk.CTkLabel(self.ram_frame, text="", font=ctk.CTkFont(weight="bold"))
        self.ram_tier.pack(side="right")
        
        self.gpu_frame = ctk.CTkFrame(self.scores_frame, fg_color="transparent")
        self.gpu_frame.pack(fill="x", pady=5)
        self.gpu_label = ctk.CTkLabel(self.gpu_frame, text="GPU: 0 pts", justify="left")
        self.gpu_label.pack(side="left")
        self.gpu_tier = ctk.CTkLabel(self.gpu_frame, text="", font=ctk.CTkFont(weight="bold"))
        self.gpu_tier.pack(side="right")

        self.disk_frame = ctk.CTkFrame(self.scores_frame, fg_color="transparent")
        self.disk_frame.pack(fill="x", pady=5)
        self.disk_label = ctk.CTkLabel(self.disk_frame, text="Storage: 0 pts", justify="left")
        self.disk_label.pack(side="left")
        self.disk_tier = ctk.CTkLabel(self.disk_frame, text="", font=ctk.CTkFont(weight="bold"))
        self.disk_tier.pack(side="right")

        self.legend_frame = ctk.CTkFrame(self.sidebar_frame, fg_color=("gray85", "gray20"))
        self.legend_frame.grid(row=2, column=0, padx=15, pady=10, sticky="ew")
        
        self.legend_title = ctk.CTkLabel(self.legend_frame, text="Tier Legend (CPU | RAM | GPU | DISK)", font=ctk.CTkFont(size=11, weight="bold"))
        self.legend_title.pack(anchor="w", padx=10, pady=(5, 2))
        
        tiers_list = [
            ("Entry", "#e74c3c", "< 10k | < 2k  | < 5k  | < 2k"),
            ("Mid", "#f39c12", "< 20k | < 3.5k| < 10k | < 5k"),
            ("High", "#2ecc71", "< 35k | < 6k  | < 18k | < 10k"),
            ("Ultra", "#9b59b6", " 35k+ |  6k+  |  18k+ | 10k+")
        ]
        
        for name, color, reqs in tiers_list:
            row = ctk.CTkFrame(self.legend_frame, fg_color="transparent")
            row.pack(fill="x", padx=10, pady=2)
            color_box = ctk.CTkLabel(row, text="■", text_color=color, font=ctk.CTkFont(size=14))
            color_box.pack(side="left")
            tier_name = ctk.CTkLabel(row, text=name, font=ctk.CTkFont(size=11, weight="bold"), width=35, anchor="w")
            tier_name.pack(side="left", padx=(5, 5))
            req_label = ctk.CTkLabel(row, text=reqs, font=ctk.CTkFont(size=11), text_color=("gray50", "gray60"))
            req_label.pack(side="right")

        self.bench_options_frame = ctk.CTkFrame(self.sidebar_frame, fg_color=("gray85", "gray20"), corner_radius=6)
        self.bench_options_frame.grid(row=3, column=0, padx=15, pady=(5, 5), sticky="ew")
        self.bench_options_frame.grid_columnconfigure((0, 1), weight=1)
        
        lbl_options = ctk.CTkLabel(self.bench_options_frame, text="Modules to Run:", font=ctk.CTkFont(size=12, weight="bold"))
        lbl_options.grid(row=0, column=0, columnspan=2, padx=10, pady=(8, 2), sticky="w")
        
        self.run_cpu_var = ctk.BooleanVar(value=True)
        self.run_ram_var = ctk.BooleanVar(value=True)
        self.run_disk_var = ctk.BooleanVar(value=True)
        self.run_gpu_var = ctk.BooleanVar(value=True) 
        
        checkbox_args = {
            "width": 60,
            "checkbox_width": 22,
            "checkbox_height": 22,
            "corner_radius": 4,
            "border_width": 2,
            "font": ctk.CTkFont(size=12, weight="bold"),
            "fg_color": "#3498db",
            "hover_color": "#2980b9"
        }
        
        ctk.CTkCheckBox(self.bench_options_frame, text="CPU", variable=self.run_cpu_var, **checkbox_args).grid(row=1, column=0, padx=(15, 5), pady=(5, 5), sticky="w")
        ctk.CTkCheckBox(self.bench_options_frame, text="RAM", variable=self.run_ram_var, **checkbox_args).grid(row=1, column=1, padx=(5, 10), pady=(5, 5), sticky="w")
        ctk.CTkCheckBox(self.bench_options_frame, text="Disk", variable=self.run_disk_var, **checkbox_args).grid(row=2, column=0, padx=(15, 5), pady=(5, 10), sticky="w")
        ctk.CTkCheckBox(self.bench_options_frame, text="GPU", variable=self.run_gpu_var, **checkbox_args).grid(row=2, column=1, padx=(5, 10), pady=(5, 10), sticky="w")

        self.benchmark_btn = ctk.CTkButton(self.sidebar_frame, text="Run Selected Benchmarks", command=self.start_benchmarks_thread)
        self.benchmark_btn.grid(row=4, column=0, padx=20, pady=(15, 10), sticky="ew")
        ToolTip(self.benchmark_btn, "Run intense multi-threaded tests on your selected components.")

        self.stop_btn = ctk.CTkButton(self.sidebar_frame, text="Stop Benchmark", command=self.stop_benchmarks, fg_color="#c0392b", hover_color="#e74c3c", state="disabled")
        self.stop_btn.grid(row=5, column=0, padx=20, pady=(0, 15), sticky="ew")

        self.status_label = ctk.CTkLabel(self.sidebar_frame, text="Status: Ready", text_color="green", font=ctk.CTkFont(size=12), wraplength=240, justify="left")
        self.status_label.grid(row=6, column=0, padx=20, pady=(5, 5), sticky="w")

        self.progress_bar = ctk.CTkProgressBar(self.sidebar_frame, mode="determinate", height=12)
        self.progress_bar.grid(row=7, column=0, padx=20, pady=(0, 15), sticky="ew")
        self.progress_bar.set(0.0)

        self.settings_btn = ctk.CTkButton(self.sidebar_frame, text="⚙️ Advanced Settings", command=self.open_settings_dialog, fg_color="transparent", text_color=("black", "white"), border_width=1, border_color=("gray75", "gray40"), hover_color=("gray80", "gray25"))
        self.settings_btn.grid(row=9, column=0, padx=20, pady=(0, 20), sticky="ew")

        # ---------------- MAIN AREA (TABS) ----------------
        self.right_container = ctk.CTkFrame(self, fg_color="transparent")
        self.right_container.grid(row=0, column=1, sticky="nsew", padx=20, pady=20)
        self.right_container.grid_columnconfigure(0, weight=1)
        self.right_container.grid_rowconfigure(0, weight=1)

        self.main_tabs = ctk.CTkTabview(self.right_container)
        self.main_tabs.grid(row=0, column=0, sticky="nsew")

        tab_search = self.main_tabs.add("🔍 Search & Optimize")
        tab_network = self.main_tabs.add("🌐 Network Speed")
        tab_local = self.main_tabs.add("🎮 My Local Games")

        self.search_tab = SearchOptimizeTab(tab_search, self)
        self.search_tab.pack(fill="both", expand=True)

        self.network_tab = NetworkSpeedTab(tab_network, self)
        self.network_tab.pack(fill="both", expand=True)

        self.local_tab = LocalGamesTab(tab_local, self)
        self.local_tab.pack(fill="both", expand=True)

    def open_settings_dialog(self):
        if self.settings_window is None or not self.settings_window.winfo_exists():
            self.settings_window = SettingsDialog(self)
        else:
            self.settings_window.focus()

    def launch_search_for_game(self, game_name):
        self.main_tabs.set("🔍 Search & Optimize")
        self.search_tab.game_entry.delete(0, 'end')
        self.search_tab.game_entry.insert(0, game_name)
        self.search_tab.optimize_game()

    def clear_cache(self, dialog):
        if os.path.exists(CACHE_FILE):
            try:
                os.remove(CACHE_FILE)
            except:
                pass
        self.cpu_score = 0
        self.ram_score = 0
        self.gpu_score = 0
        self.disk_score = 0
        self.update_score_displays()
        self.search_tab.on_tab_change()
        messagebox.showinfo("Success", "Cache cleared successfully. Scores reset to 0.")
        dialog.destroy()

    def open_edit_dialog(self):
        dialog = ctk.CTkToplevel(self)
        dialog.title("Edit Scores")
        dialog.geometry("300x300")
        dialog.attributes("-topmost", True)
        
        dialog.grid_columnconfigure(1, weight=1)
        
        ctk.CTkLabel(dialog, text="CPU Score:").grid(row=0, column=0, padx=10, pady=10, sticky="w")
        cpu_entry = ctk.CTkEntry(dialog)
        cpu_entry.insert(0, str(self.cpu_score))
        cpu_entry.grid(row=0, column=1, padx=10, pady=10, sticky="ew")
        
        ctk.CTkLabel(dialog, text="RAM Score:").grid(row=1, column=0, padx=10, pady=10, sticky="w")
        ram_entry = ctk.CTkEntry(dialog)
        ram_entry.insert(0, str(self.ram_score))
        ram_entry.grid(row=1, column=1, padx=10, pady=10, sticky="ew")
        
        ctk.CTkLabel(dialog, text="GPU Score:").grid(row=2, column=0, padx=10, pady=10, sticky="w")
        gpu_entry = ctk.CTkEntry(dialog)
        gpu_entry.insert(0, str(self.gpu_score))
        gpu_entry.grid(row=2, column=1, padx=10, pady=10, sticky="ew")

        ctk.CTkLabel(dialog, text="Disk Score:").grid(row=3, column=0, padx=10, pady=10, sticky="w")
        disk_entry = ctk.CTkEntry(dialog)
        disk_entry.insert(0, str(self.disk_score))
        disk_entry.grid(row=3, column=1, padx=10, pady=10, sticky="ew")
        
        def save_scores():
            try:
                self.cpu_score = int(cpu_entry.get())
                self.ram_score = int(ram_entry.get())
                self.gpu_score = int(gpu_entry.get())
                self.disk_score = int(disk_entry.get())
                self.save_cached_data()
                self.update_score_displays()
                self.search_tab.on_tab_change()
                dialog.destroy()
            except ValueError:
                messagebox.showerror("Error", "Please enter valid numbers.")
                
        ctk.CTkButton(dialog, text="Save", command=save_scores).grid(row=4, column=0, columnspan=2, pady=20)

    def update_score_displays(self):
        cpu_t, cpu_c = self.get_tier_info(self.cpu_score, "CPU")
        cpu_name = self.actual_specs.get("CPU", "Unknown CPU")
        
        ram_t, ram_c = self.get_tier_info(self.ram_score, "RAM")
        ram_gb = self.actual_specs.get("RAM", 0)
        
        gpu_t, gpu_c = self.get_tier_info(self.gpu_score, "GPU")
        gpu_name = self.actual_specs.get("GPU", "Unknown GPU")

        disk_t, disk_c = self.get_tier_info(self.disk_score, "DISK")
        
        self.cpu_label.configure(text=f"CPU: {self.cpu_score} pts\n({cpu_name})")
        self.cpu_tier.configure(text=cpu_t, text_color=cpu_c)
        
        self.ram_label.configure(text=f"RAM: {self.ram_score} pts\n({ram_gb} GB)")
        self.ram_tier.configure(text=ram_t, text_color=ram_c)
        
        self.gpu_label.configure(text=f"GPU: {self.gpu_score} pts\n({gpu_name})")
        self.gpu_tier.configure(text=gpu_t, text_color=gpu_c)

        self.disk_label.configure(text=f"Storage: {self.disk_score} pts\n(NVMe/SSD)")
        self.disk_tier.configure(text=disk_t, text_color=disk_c)

    def start_benchmarks_thread(self):
        if not any([self.run_cpu_var.get(), self.run_ram_var.get(), self.run_disk_var.get(), self.run_gpu_var.get()]):
            messagebox.showinfo("Info", "Please select at least one benchmark to run.")
            return

        self.benchmark_btn.configure(state="disabled")
        self.stop_btn.configure(state="normal")
        self.status_label.configure(text="Status: Initializing benchmarks...", text_color="orange")
        self.progress_bar.set(0.0)
        threading.Thread(target=self.run_benchmarks_subprocess, daemon=True).start()

    def stop_benchmarks(self):
        if self.benchmark_process and self.benchmark_process.poll() is None:
            try:
                self.benchmark_process.terminate()
            except Exception:
                pass
        self.status_label.configure(text="Status: Benchmark aborted", text_color="red")
        self.progress_bar.set(0.0)
        self.benchmark_btn.configure(state="normal")
        self.stop_btn.configure(state="disabled")

    def run_benchmarks_subprocess(self):
        try:
            cmd = [sys.executable]
            if not getattr(sys, 'frozen', False):
                cmd.extend(["-u", os.path.abspath(__file__), "--run-benchmarks"])
            else:
                cmd.extend(["--run-benchmarks"])

            if self.run_cpu_var.get(): cmd.append("--run-cpu")
            if self.run_ram_var.get(): cmd.append("--run-ram")
            if self.run_disk_var.get(): cmd.append("--run-disk")
            if self.run_gpu_var.get(): cmd.append("--run-gpu")

            self.benchmark_process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1
            )

            for line in self.benchmark_process.stdout:
                line_str = line.strip()
                if line_str.startswith("PROGRESS:"):
                    content = line_str.replace("PROGRESS:", "").strip()
                    
                    pct_val = 0.0
                    msg = content
                    if "| PCT:" in content:
                        parts = content.split("| PCT:")
                        msg = parts[0].strip()
                        try:
                            pct_val = float(parts[1].strip()) / 100.0
                        except ValueError:
                            pct_val = 0.0

                    self.after(0, lambda m=msg, p=pct_val: self.update_benchmark_progress(m, p))

            self.benchmark_process.wait()
            if self.benchmark_process.returncode != 0:
                if self.benchmark_process.returncode != 1:
                    raise Exception("Subprocess crashed during execution")

            self.load_cached_data()
            self.after(0, self.update_scores_ui)
        except Exception as e:
            err_msg = str(e)
            if "aborted" not in err_msg.lower():
                self.after(0, lambda: messagebox.showerror("Error", f"Benchmark failed: {err_msg}"))
            self.after(0, lambda: self.status_label.configure(text="Status: Ready", text_color="green"))
            self.after(0, lambda: self.progress_bar.set(0.0))
        finally:
            self.benchmark_process = None
            self.after(0, lambda: self.benchmark_btn.configure(state="normal"))
            self.after(0, lambda: self.stop_btn.configure(state="disabled"))

    def update_benchmark_progress(self, msg, progress_float):
        self.status_label.configure(text=f"Status: {msg}", text_color="orange")
        self.progress_bar.set(progress_float)

    def update_scores_ui(self):
        self.update_score_displays()
        self.status_label.configure(text="Status: Benchmarks complete!", text_color="green")
        self.progress_bar.set(1.0)
        self.search_tab.on_tab_change()

if __name__ == "__main__":
    multiprocessing.freeze_support()
    
    if "--run-benchmarks" in sys.argv:
        from run_benchmarks import run_gui_benchmarks
        run_gui_benchmarks()
    else:
        app = HardwareOptimizerApp()
        app.mainloop()